services:
  backend:
    build:
      context: ./notev2-backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notesdb
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=notesdb
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./notev2-frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'

volumes:
  postgres_data: